### ISSUE TITLE
[BUG] Ceizak Battlegrounds .obj produces strange results when viewed in object viewers

### ISSUE THREAD

**Issue by Darkdoom22** [Xenonsmurf/FFxi-Navmesh-Builder#7]
**Describe the bug**
After building the Ceizak Battlegrounds object file, opening it in recast or another object viewer will display what appears to be a straight line and nothing else.

**To Reproduce**
Build an object file for Ceizak Battlegrounds

**Expected behaviour**
The zone object to be properly displayed when viewed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows10/Windows11 

**Additional context**
Bug Cause: This problem appears to be caused by a set of vertices in the ceizak .dat data with extremely small Z values (approx. -9932914.0f)

Possible Solution: modifying the vertice parsing code to skip adding these vertices to the vertice list results in an object file being dumped that is properly rendered when viewed.

**Comment by MurphyCodes** [comment]
Well spotted, This has now been fixed. 

See here: 
https://github.com/MurphyCodes/FFxi-Navmesh-Builder/blob/main/src/FFXI%20Navmesh%20Builder/Common/dat/Types/MZB.cs#L384

all collision meshes have been remade to test if this fix alters other meshes, it does not.
All collision.obj's now build without issue.

thank you for spotting the issue and the solution!.

regards.

/xen
